services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 375632
      MYSQL_DATABASE: tamago
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      MYSQL_DATASOURCE_URL: jdbc:mysql://mysql:3306/tamago?useSSL=false&serverTimezone=UTC
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 375632
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    entrypoint: ["sh", "-c", "sleep 10 && java -jar app.jar"]

networks:
  app-network:

volumes:
  db_data: