services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile 경로를 명확히 설정
    container_name: spring-app
    env_file:
      - .env  # .env 파일을 통해 환경 변수를 로드
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: