server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tamago?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: siyoon
    password: 375632
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  #    defer-datasource-initialization: true
  mvc:
    cors:
      mappings:
        - path: "/**"
          allowed-origins: "https://api.neon7.site"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  sql:
    init:
      mode: always
      platform: mysql