spring:
  datasource:
#    url: jdbc:mysql://3.39.237.227:3306/event_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: siyoon
    url: jdbc:mysql://host.docker.internal:3306/event_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 375632
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers