spring:
  datasource:
    url: jdbc:mysql://3.39.237.227:3306/event_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: siyoon
    password: 375632
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 3.39.237.227
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: 3.39.237.227
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus