server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/tamago?useSSL=false&serverTimezone=UTC
    username: root
    password: 375632
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    cors:
      mappings:
        - path: "/**"
          allowed-origins: "https://api.neon7.site"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  sql:
    init:
      mode: always
      platform: mysql