server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    cors:
      mappings:
        - path: "/**"
          allowed-origins: "https://neon7.site"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  sql:
    init:
      mode: always
      platform: mysql