server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/event_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: siyoon
    password: 375632
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true