name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle 캐시 설정
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew bootJar

      # SSH 키 설정
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      # Dockerfile, docker-compose.yml, JAR 파일을 EC2로 전송
      - name: Upload Files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem Dockerfile ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem docker-compose.yml ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem build/libs/tamago-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      # EC2에서 Docker Compose 빌드 및 실행
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF