name: Deploy Spring Boot App to EC2 using Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      # Docker Compose 파일과 Dockerfile을 EC2로 전송 (scp 사용)
      - name: Copy files to EC2
        run: |
          scp -i ${{ secrets.EC2_KEY }} -o StrictHostKeyChecking=no docker-compose.yml Dockerfile ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/spring-app/

      # EC2에 SSH 접속하여 Docker Compose 실행
      - name: SSH and deploy with Docker Compose
        run: |
          ssh -i ${{ secrets.EC2_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ~/spring-app/
            docker-compose down
            docker-compose up -d --build
          EOF